### ISSUE TITLE
Does not work in cart

### ISSUE THREAD

**Issue by victor-e-claeys** [somewherewarm/woocommerce-product-bundles-min-max-items#3] opened 2017-10-20 15:13 UTC
This plugin works great when on the product but does not validate quantities that are changed in the cart.

**Comment by franticpsyx** [comment] 2017-10-24 23:41
Confirmed :) PB cart quantities are editable since version 5.5, which was just released. We need to add support for this in Min/Max Items.

**Comment by franticpsyx** [comment] 2017-11-02 15:39
closed in 2d6b3619da5636e26dfbfd6e1a867a9dd4b57b25

**Closed by franticpsyx** 2017-11-02 15:39 UTC
Labels: bug:confirmed, priority:high, scale:medium, status:in-progress
